[platformio]
default_envs = transmitter

[env]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:transmitter]
build_src_filter =
  +<transmitter/>
lib_deps =
  lovyan03/LovyanGFX

[env:receiver]
build_src_filter =
  +<receiver/>
lib_deps =
  okalachev/MAVLink
